### ISSUE TITLE
system message in a batch

### ISSUE THREAD

**Issue by suguanyi** [SpellcraftAI/oaib#16]
Thank you for the excellent code; it's a very useful library. I have a question regarding batch creating. Is it possible to include a system message in a batch? Specifically, I want to reduce the number of tokens in a batch by adding the repeated part of a user message as a system message. Is there a method to achieve this?

**Comment by ctjlewis** [comment]
You can do this by just batch.add()ing a system message, but it won't reduce the number of tokens. Each measurement is taken independently.

We don't actively maintain this library. OpenAI released the [Batch API](https://platform.openai.com/docs/guides/batch) shortly after we put this out, have you considered using that?

**Comment by suguanyi** [comment]
Thank you for your response! Yes, I have considered using the Batch API, but I've encountered an issue: I can only add one user message to a batch. When I try to add more than two user messages, OpenAI rejects the request. Therefore, I turned to your library to see if I could add multiple user messages to a batch. Do you have any insights on this problem?


---- Replied Message ----
| From | ***@***.***> |
| Date | 8/28/2024 23:28 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [SpellcraftAI/oaib] system message in a batch (Issue #16) |

You can do this by just batch.add()ing a system message, but it won't reduce the number of tokens. Each measurement is taken independently.

We don't actively maintain this library. OpenAI released the Batch API shortly after we put this out, have you considered using that?

**Comment by ctjlewis** [comment]
You can add an entire conversation to the batch by putting the whole context in for `messages`:

```
        messages=[{"role": "user", "content": "say hello"}, ...]
```
