### ISSUE TITLE
Thank you a lot

### ISSUE THREAD

**Issue by pi-infected** [SpellcraftAI/oaib#17]
Well, you don't know how many hours you saved me. 

It is just a thank you message. I use OAIB in my MVP and it's great. It is invaluable to absord peaks of demands. 

Keep the good work. 

My use case, in case it is of interest to you 

I made a openai server with OAIB, that acccept batchs, process them in a queue, and transfert the post processing to an arbitrary celery task. 

As celery hates multithreading / multiprocessing / async, I use it to quickly difuse big amount of openai requests that I need to process without blocking celery workers in waiting mode (and making my software bloated with waiting workers). 

And the cherry on top of the cake, I'am sure to never get API ratelimited.

**Comment by ctjlewis** [comment]
Thanks man, I really appreciate that. Gonna close just to keep it organized. I followed you on Twitter too.
