### ISSUE TITLE
larger chat requests cause errors

### ISSUE THREAD

**Issue by jvmncs** [SpellcraftAI/oaib#4]
hi, tried this out today and found that both Batch and Auto aren't functioning properly for chat requests with longer messages. here's an adapted example from the existing Auto test:
```
import oaib

import pytest


@pytest.mark.asyncio
async def test_auto():
    batch = oaib.Auto()

    n = 20
    m = 20
    for i in range(n):
        await batch.add("chat.completions.create", model="gpt-4", messages=[{"role": "user", "content": "say hello " * m}])

    chats = await batch.run()
    assert len(chats) == n, f"Chat batch should return {n} results, got {len(chats)}"
    print(chats)

    chat = chats.iloc[0].get("result")
    assert chat['choices'], "Should get valid chat completions"

```
for `m~=20`, this test gets pretty flaky. in practice I was trying to use it with messages of >1000 tokens, which fails more reliably

**Comment by ctjlewis** [comment]
1s, looking into it.

Can you post `oaib.txt`? I think they're just throwing and so do not make it into the observations dataset. I also think it might not be catching errors and reading the token usage from those.

**Comment by ctjlewis** [comment]
Can you post `oaib.txt`? I think they're just throwing and being removed. I also think it might not be catching errors and reading the token usage from those.

**Comment by ctjlewis** [comment]
@jvmncs - please try v1.0.1.

```shell
pip3 install -U oaib
```

**Comment by jvmncs** [comment]
fixed, nice!
